"""add user field to funded_farms and updates

Revision ID: 51680706e697
Revises: de9729bb8a24
Create Date: 2020-01-20 18:50:50.157937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51680706e697'
down_revision = 'de9729bb8a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm', sa.Column('status', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
