"""empty message

Revision ID: 77f6e3dafd21
Revises: b5b68a76a600
Create Date: 2020-01-19 18:30:06.282836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f6e3dafd21'
down_revision = 'b5b68a76a600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funded_farm', sa.Column('farm_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funded_farm', 'farm_id')
    # ### end Alembic commands ###
