"""add new fields to funded table

Revision ID: b5b68a76a600
Revises: bc461fc59bcf
Create Date: 2020-01-18 17:42:01.137242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b68a76a600'
down_revision = 'bc461fc59bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funded_farm', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('funded_farm', sa.Column('payout', sa.Float(), nullable=True))
    op.add_column('funded_farm', sa.Column('units', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funded_farm', 'units')
    op.drop_column('funded_farm', 'payout')
    op.drop_column('funded_farm', 'amount')
    # ### end Alembic commands ###
