"""add duration field

Revision ID: bc461fc59bcf
Revises: 4fc2937e4cee
Create Date: 2020-01-18 14:44:31.459654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc461fc59bcf'
down_revision = '4fc2937e4cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm', sa.Column('duration', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm', 'duration')
    # ### end Alembic commands ###
