"""Add new fields

Revision ID: de9729bb8a24
Revises: 77f6e3dafd21
Create Date: 2020-01-19 18:53:15.514603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de9729bb8a24'
down_revision = '77f6e3dafd21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm', sa.Column('status', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm', 'status')
    # ### end Alembic commands ###
