"""Rename farm_name to name in farms table

Revision ID: df38f48fbb22
Revises: c7ff67f6f2ab
Create Date: 2020-01-11 21:33:48.397218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df38f48fbb22'
down_revision = 'c7ff67f6f2ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_column('farms', 'farm_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('farm_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('farms', 'name')
    # ### end Alembic commands ###
