"""empty message

Revision ID: ed68a1804aed
Revises: 7d265b075c57
Create Date: 2020-01-11 19:02:41.496979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed68a1804aed'
down_revision = '7d265b075c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('farms', sa.Column('harvest_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'harvest_time')
    op.drop_column('farms', 'active')
    # ### end Alembic commands ###
